### PR TITLE
Custom popup position and auto center

### PR DESCRIPTION
**Pull request by rlamana**
This PR adds two new optional properties: `popupHeight` and `popupWidth` to customize popup window position. It also automatically centers the popup.

### CODE REVIEW

**Comment by rlamana** [comment]
@kruppel any feedback/review on this PR?

**Comment by o2sh** [comment]
Yes, plz merge

**Comment by rlamana** [comment]
again, can this be reviewed and merged? It's a very simple change and very much needed. @kruppel?

**Comment by rlamana** [comment]
Closing since these PR's are unattended and the project seems to be abandoned. 
The changes can be found in this other package: https://www.npmjs.com/package/react-login-github

**Pull request closed without merging**
